services:
  evacuation_planning_and_monitoring_api:
    image: ${DOCKER_REGISTRY-}evacuation-planning-and-monitoring-api
    build:
      context: Evacuation_Planning_and_Monitoring_API
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    environment:
      - VaultUri=https://evacuationazurekey.vault.azure.net/