services:
  evacuation_planning_and_monitoring_api:
    image: ${DOCKER_REGISTRY-}evacuationplanningandmonitoringapi
    build:
      context: Evacuation_Planning_and_Monitoring_API
      dockerfile: Dockerfile
