# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - evacuation-planning-and-monitoring-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://epmapiregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f6d6606484e34c28bf4d8fbdb40de591 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_453bf5803d6f46f0a611e8fd96da994f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: epmapiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f6d6606484e34c28bf4d8fbdb40de591 }}/epm-dotnet-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'evacuation-planning-and-monitoring-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cba2e83894b84724bab64e53831cae11 }}
        images: 'epmapiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f6d6606484e34c28bf4d8fbdb40de591 }}/epm-dotnet-api:${{ github.sha }}'