# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - evacuation-planning-and-monitoring-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://epmazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b4a71ee8d22041679c3d7d2d69d8e534 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8a9d329ed0c1498fbe9c93f3328ca9b7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: epmazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b4a71ee8d22041679c3d7d2d69d8e534 }}/evacuation-planning-and-monitoring-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'evacuation-planning-and-monitoring-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_720f6ab4fba94622ab271344eaf0e042 }}
        images: 'epmazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b4a71ee8d22041679c3d7d2d69d8e534 }}/evacuation-planning-and-monitoring-api:${{ github.sha }}'