# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - evacuation-planning-and-monitoring-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://epmregitry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ddd4a5dce35746798ffe5b30ca0e3046 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_95b05d115a3244ed99e4e21ea6cd3aba }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: epmregitry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ddd4a5dce35746798ffe5b30ca0e3046 }}/evacuationplanningandmonitoringapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'evacuation-planning-and-monitoring-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c386c133ad1a4d64a730e005c966bcd3 }}
        images: 'epmregitry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ddd4a5dce35746798ffe5b30ca0e3046 }}/evacuationplanningandmonitoringapi:${{ github.sha }}'